### ISSUE TITLE
1 Portrait with 1 Landscape not showing properly

### ISSUE THREAD

**Issue by canvas-vikas** [jerryc-nguyen/ng-photo-grid#1]
Hi Jerryc, first of all thanks for the wonderful control. I am using this in our project and finding it very nice, just 1 case I noticed is when there are 2 pics, 1 of them is portrait and another is landscape, the display shows 2 horizontally splits in which portrait photo gets cut, see the screenshot attached:

![image](https://cloud.githubusercontent.com/assets/11735093/10867771/e7054bfc-809a-11e5-9e81-edf16242ff90.png)

this is the configuration I am using, I tried using 2big configuration option also but didn't help: 
scope.gridOptions = {
                    urlKey      :     "original_url",
                    sortKey     :     "nth",
                    onClicked   :     function(image) {
                        //
                    },
                    onBuilded   :     function() {
                        scope.isBuildingGrid = false;
                    },
                    margin      :     2,
                    maxLength   :     5
                }

I would really appreciate your timely help in this issue.

**Comment by jerryc-nguyen** [comment]
yes, I will take a look on this as soon as possible.
Can you post 2 image above for me easy to reproduce the issue? 
Also, the 2bigs only occur when 2 first images were squared and your images count should be greater or equals to 5.
Many thanks for your feedback.

**Comment by canvas-vikas** [comment]
Hi Jerryc, thanks for your quick reply, here are the pics for your reference:

Portrait pic: http://cdn.testkanvz.com/images/content/medium/jroy-Nyq8l3a-g.JPG
Landscape pic: http://cdn.testkanvz.com/images/content/medium/jroy-NklKghaZe.JPG

thanks again for the support.

**Comment by jerryc-nguyen** [comment]
Hi Vikas, 
I tried to reproduce the issue by your images but it's displayed correctly in my side.
I wonder about your code has been updated with master branch?
Also, I applied css to grid wrapper's width with these size: 250px -> 600px and it's display with no any problem.
This is the result:
![screen shot 2015-11-03 at 3 02 10 am](https://cloud.githubusercontent.com/assets/10796606/10892674/6144a632-81d7-11e5-9ace-e7ebb23616f4.png)

So please give me more details about your issues if you still meet them.
Thanks.

**Comment by canvas-vikas** [comment]
Hi Jerry, 
I downloaded the code .zip file from your github repository (using the "Download Zip" button):
![image](https://cloud.githubusercontent.com/assets/11735093/10902230/b0974b42-8220-11e5-9e0d-fbd47c9a0615.png)

then I put my images in app.js and ran the index.html example and this is what I see the output:
![image](https://cloud.githubusercontent.com/assets/11735093/10902266/4179dbde-8221-11e5-9941-a342a250fd30.png)

Can you please see if this .zip file code is somehow different than what you are using. 
Please provide your sample working code it would be very helpful.

**Comment by canvas-vikas** [comment]
Hi Jerry, I am really time crunched on this issue, your early reply will be really helpful.

Thanks in advance.. !!

**Comment by jerryc-nguyen** [comment]
Sorry for late reply, I am quite busy.
I just push the workaround for this on master, please take a look.
I will dig into this issue to find more suitable solution on the weekend.
Thanks.

**Comment by canvas-vikas** [comment]
thanks for the quick fix for the issue, I have implemented your workaround for now and its working. 
Waiting for your final fix for this issue.

Also, in this case (1 portrait and 1 landscape), can the output look like this:
![image](https://cloud.githubusercontent.com/assets/11735093/10969595/74b4a93c-83ef-11e5-8f15-770426fed1d4.png)

Just curious how the vertical and horizontal tiling is working. We need this for our app. Thanks so much for your efforts. This control is so helpful. 

Waiting eagerly for your reply.

**Comment by jerryc-nguyen** [comment]
Yes, you are right, this is the bug. The first cell shape will be build base on the first image. So it should be vertical. Your grid look quite good and output as my expected. So I will update in this weekend.
Thanks.

**Comment by canvas-vikas** [comment]
Thanks for your quick response, I will wait for your update.

**Comment by jerryc-nguyen** [comment]
Hi Vikas, I just updated module, there are some fixes and improvements. 
So please close the issue if you find it's working.
Thanks.

**Comment by canvas-vikas** [comment]
Hi Jerryc, Thanks for the much awaited fix, I am closing this issue now. 
Thanks again for your help !!
