### ISSUE TITLE
If ng-photogrid uses is given one picture if throws an error

### ISSUE THREAD

**Issue by rdosanjh** [jerryc-nguyen/ng-photo-grid#2]
When trying to render a single picture it throws the following 
Uncaught TypeError: Cannot read property 'small' of undefined

**Comment by OTSimple** [comment]
Hi @rdosanjh , did you find any solution for this issue ?
If so, please let me know. I'm also facing it.
Thanks

**Comment by jerryc-nguyen** [comment]
hi, I just merge the patch from rdosanjh, please check out again on master branch. I will improve it later.
