### ISSUE TITLE
How to make this plugin responsive

### ISSUE THREAD

**Issue by hirbod** [jerryc-nguyen/ng-photo-grid#4]
Hi,

any approach how to make this whole thing work responsive?

**Comment by jerryc-nguyen** [comment]
Yes, we can rebuild the grid when screen size changes. So I think we will add option to support this feature. If you can implement, please PR. I will take a look on this on the weekend. Thanks.

**Comment by hirbod** [comment]
Did you manage to incoporate this? @jerryc-nguyen
